export const FEATURED_PRODUCTS = [
  {
    id: 'p1',
    name: 'Chaqueta Oversize',
    price: '29 €',
    originalPrice: '89 €',
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=300&q=80',
    store: 'Retro Vintage',
    stockRemaining: 1,
    maxStock: 5,
    stockText: '¡Última disponible en tienda!',
    rating: '4.8',
    reviewsCount: '(1.2K)',
    popularBadge: '#1 Moda',
    cerclePlus: true
  },
  {
    id: 'p2',
    name: 'Zapatillas Blancas',
    price: '45 €',
    originalPrice: '120 €',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=300&q=80',
    store: 'Urban Sneaks',
    stockRemaining: 2,
    maxStock: 8,
    stockText: 'Solo quedan 2 unidades',
    rating: '4.6',
    reviewsCount: '(800)',
    popularBadge: 'Destacado',
    cerclePlus: false
  },
  {
    id: 'p3',
    name: 'Bolso de Piel',
    price: '55 €',
    originalPrice: '180 €',
    image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=300&q=80',
    store: 'Leather Works',
    stockRemaining: 1,
    maxStock: 6,
    stockText: 'Único en stock local',
    rating: '4.5',
    reviewsCount: '(250)',
    popularBadge: 'Exclusivo',
    cerclePlus: true
  },
  {
    id: 'p4',
    name: 'Vestido Floral',
    price: '19 €',
    originalPrice: '65 €',
    image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=300&q=80',
    store: 'Boho Chic',
    stockRemaining: 3,
    maxStock: 10,
    stockText: 'Últimas 3 unidades residuales',
    rating: '4.9',
    reviewsCount: '(3.1K)',
    popularBadge: 'Tendencia',
    cerclePlus: true
  },
  {
    id: 'p5',
    name: 'Gafas de Sol Pro',
    price: '12 €',
    originalPrice: '40 €',
    image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&w=300&q=80',
    store: 'Specs Studio',
    stockRemaining: 2,
    maxStock: 7,
    stockText: 'Solo 2 disponibles',
    rating: '4.7',
    reviewsCount: '(150)',
    popularBadge: 'Clásico',
    cerclePlus: false
  },
  {
    id: 'p6',
    name: 'Jersey de Lana',
    price: '22 €',
    originalPrice: '70 €',
    image: 'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?auto=format&fit=crop&w=300&q=80',
    store: 'Urban Sneaks',
    stockRemaining: 6,
    maxStock: 10,
    stockText: 'Quedan 6 unidades',
    rating: '4.4',
    reviewsCount: '(430)',
    popularBadge: 'Básico',
    cerclePlus: false
  },
  {
    id: 'p7',
    name: 'Vaqueros Slim',
    price: '25 €',
    originalPrice: '75 €',
    image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=300&q=80',
    store: 'Retro Vintage',
    stockRemaining: 8,
    maxStock: 12,
    stockText: 'Quedan 8 unidades',
    rating: '4.8',
    reviewsCount: '(1.1K)',
    popularBadge: '#2 Moda',
    cerclePlus: true
  },
  {
    id: 'p8',
    name: 'Camiseta Algodón',
    price: '9 €',
    originalPrice: '27 €',
    image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=300&q=80',
    store: 'Boho Chic',
    stockRemaining: 5,
    maxStock: 10,
    stockText: 'Quedan 5 unidades',
    rating: '4.7',
    reviewsCount: '(680)',
    popularBadge: 'Fresco',
    cerclePlus: true
  }
];

export type FeaturedProduct = (typeof FEATURED_PRODUCTS)[number];
