import { Dimensions, StyleSheet } from 'react-native';

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');

export const DEAL_CARD_WIDTH = 274;
export const DEAL_IMAGE_HEIGHT = 142;
export const STORE_IMAGE_HEIGHT = Math.round((SCREEN_WIDTH - 40) * (9 / 16));

export { SCREEN_WIDTH, SCREEN_HEIGHT };

export const homeStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#FFFFFF' },
  contentCard: { backgroundColor: 'transparent', borderTopLeftRadius: 22, borderTopRightRadius: 22, paddingHorizontal: 20, paddingTop: 0, minHeight: SCREEN_HEIGHT },

  headerContainer: {
    backgroundColor: '#FFFFFF',
    zIndex: 100,
  },
  topRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 14,
    gap: 8,
    zIndex: 100
  },
  deliverySelector: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F3F4F6',
    paddingHorizontal: 12,
    height: 40,
    borderRadius: 22,
    gap: 6,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    flex: 1,
  },
  deliveryText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#1F2937',
  },
  headerButtonActive: {
    backgroundColor: '#FDF2F4',
    borderColor: '#5B2333',
  },
  searchBarContainer: {
    paddingHorizontal: 20,
    paddingBottom: 16,
    backgroundColor: 'transparent',
  },
  searchBarInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F7F7F7',
    borderRadius: 22,
    paddingHorizontal: 12,
    height: 44,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 14.5,
    fontWeight: '600',
    color: '#333333',
    padding: 0,
  },
  clearSearchButton: {
    padding: 4,
  },
  emptyStateContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
    paddingHorizontal: 20,
    backgroundColor: '#F9FAFB',
    borderRadius: 22,
    borderWidth: 1,
  },
  emptyStateIconBadge: {
    width: 48,
    height: 48,
    borderRadius: 22,
    backgroundColor: '#E5E7EB',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  emptyStateTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#333333',
    marginBottom: 8,
  },
  emptyStateText: {
    fontSize: 13.5,
    color: '#6B7280',
    textAlign: 'center',
    lineHeight: 19,
  },
  headerButton: {
    width: 40,
    height: 40,
    borderRadius: 22,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  pointsPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    height: 40,
    backgroundColor: '#FDF2F4',
    borderWidth: 1,
    borderColor: '#FDF2F4',
    borderRadius: 22,
    paddingHorizontal: 12,
  },
  pointsPillText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#5B2333',
  },

  categoriesWrapper: { marginHorizontal: -20, marginBottom: 24 },
  categoriesContainer: { paddingHorizontal: 20, gap: 12, paddingVertical: 6 },
  categoryItem: { alignItems: 'center', width: 62, position: 'relative' },
  categorySquare: {
    width: 62,
    height: 62,
    borderRadius: 22,
    backgroundColor: '#F7F7F7',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'transparent',
    marginBottom: 6,
  },
  categorySquareSelected: {
    backgroundColor: '#FFFFFF',
    borderColor: '#5B2333',
    borderWidth: 1.5,
  },
  categoryEmoji: { fontSize: 26 },
  categoryText: { fontSize: 11.5, fontWeight: '600', color: '#6B7280', textAlign: 'center' },
  categoryTextSelected: {
    color: '#5B2333',
    fontWeight: '800',
  },
  categoryActiveDot: {
    width: 6,
    height: 4,
    borderRadius: 22,
    backgroundColor: '#5B2333',
    marginTop: 4,
  },
  categorySquareAI: {
    backgroundColor: '#EEF2FF',
    borderColor: '#6366F1',
    borderWidth: 1.5,
  },
  categoryTextAI: {
    color: '#4F46E5',
    fontWeight: '700',
  },

  mainPromoWrapper: { marginBottom: 24 },
  mainPromoCard: {
    height: 180,
    borderRadius: 22,
    overflow: 'hidden',
    backgroundColor: '#F3F4F6',
    justifyContent: 'flex-end',
    padding: 20,
    borderWidth: 1,
    borderColor: '#E5E7EB'
  },
  mainPromoOverlay: { zIndex: 2 },
  mainPromoTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: '#FFFFFF',
    marginBottom: 4,
    textShadowColor: 'rgba(0,0,0,0.25)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3
  },
  mainPromoSubtitle: { fontSize: 13, fontWeight: '600', color: '#FFFFFF', opacity: 0.95 },
  promoBadge: {
    position: 'absolute',
    top: 16,
    left: 16,
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 22,
    zIndex: 2
  },
  promoBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1,
    textTransform: 'uppercase'
  },
  paginationDots: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 6, marginTop: 16 },
  dot: { width: 6, height: 6, borderRadius: 22, backgroundColor: '#E5E7EB' },
  dotActive: { width: 18, height: 6, borderRadius: 22, backgroundColor: '#1F2937' },

  sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 },
  sectionTitle: { fontSize: 18, fontWeight: '800', color: '#1A1A1A' },
  seeAllButton: {
    backgroundColor: '#F3F4F6',
    paddingHorizontal: 12,
    height: 32,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    justifyContent: 'center',
    alignItems: 'center'
  },
  seeAllText: { fontSize: 12, fontWeight: '600', color: '#1F2937' },

  storesList: { gap: 20, marginBottom: 24 },
  storeCard: {
    width: '100%',
    backgroundColor: '#FFFFFF',
    paddingBottom: 4,
  },
  storeImageContainer: {
    width: '100%',
    height: STORE_IMAGE_HEIGHT,
    backgroundColor: '#F3F4F6',
    borderRadius: 22,
    overflow: 'hidden',
  },
  storeImage: {
    width: '100%',
    height: '100%',
  },
  storeInfo: {
    paddingHorizontal: 2,
    paddingTop: 10,
    gap: 4,
  },
  storeTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    minWidth: 0,
  },
  stampBadgeOnImage: {
    position: 'absolute',
    top: 10,
    left: 10,
    backgroundColor: '#FEF3C7',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 22,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3.5,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1.5 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  stampBadgeTextOnImage: {
    fontSize: 10.5,
    fontWeight: '800',
    color: '#111827',
  },
  storeDistancePill: {
    fontSize: 12,
    fontWeight: '600',
    color: '#4B5563',
    flexShrink: 0,
    paddingTop: 2,
  },
  storeDeliveryText: {
    fontSize: 12,
    fontWeight: '500',
    color: '#9CA3AF',
    flexShrink: 1,
    minWidth: 0,
  },
  popularBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ECFDF5',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 22,
  },
  popularBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#047857',
  },

  horizontalSectionWrapper: { marginHorizontal: -20, marginBottom: 24 },
  horizontalSectionContainer: { paddingHorizontal: 20, gap: 14 },

  flashSectionWrapper: {
    marginHorizontal: -20,
    paddingVertical: 8,
    marginBottom: 24,
  },

  dealCard: {
    width: DEAL_CARD_WIDTH,
    backgroundColor: '#FFFFFF',
    paddingBottom: 4,
  },
  dealImageContainer: {
    width: '100%',
    height: DEAL_IMAGE_HEIGHT,
    backgroundColor: '#F3F4F6',
    borderRadius: 22,
    overflow: 'hidden',
    position: 'relative',
  },
  favButton: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 26,
    height: 26,
    borderRadius: 22,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1.5 },
    shadowOpacity: 0.12,
    shadowRadius: 2,
    elevation: 2,
    zIndex: 3,
  },

  dealImage: { width: '100%', height: '100%' },
  discountBadge: {
    position: 'absolute',
    top: 8,
    left: 8,
    backgroundColor: 'rgba(17, 24, 39, 0.72)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 22,
    zIndex: 2,
  },
  discountText: { color: '#FFFFFF', fontSize: 11, fontWeight: '700' },
  dealInfo: {
    paddingHorizontal: 2,
    paddingTop: 10,
    gap: 4,
  },
  dealHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  dealHeaderCopy: {
    flex: 1,
    minWidth: 0,
    gap: 4,
    paddingRight: 2,
  },
  dealNameText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#111827',
    letterSpacing: -0.2,
    lineHeight: 19,
    flexShrink: 1,
    minWidth: 0,
  },
  dealMetaLine: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    minWidth: 0,
  },
  dealStoreText: {
    fontSize: 12,
    fontWeight: '500',
    color: '#9CA3AF',
    flexShrink: 1,
    minWidth: 0,
  },
  dealMetaDot: {
    fontSize: 12,
    color: '#D1D5DB',
    fontWeight: '600',
    flexShrink: 0,
  },
  dealMetaIcon: {
    flexShrink: 0,
  },
  dealPriceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    width: '100%',
    minWidth: 0,
    marginTop: 1,
  },
  dealPriceGroup: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 6,
    flexShrink: 0,
  },
  dealStockBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#FFFBEB',
    borderRadius: 22,
    paddingHorizontal: 6,
    paddingVertical: 3,
    flexShrink: 1,
    minWidth: 0,
  },
  dealStockBannerRight: {
    marginLeft: 'auto',
  },
  dealStockDot: {
    width: 5,
    height: 5,
    borderRadius: 22,
    backgroundColor: '#F59E0B',
    flexShrink: 0,
  },
  dealStockHint: {
    fontSize: 11,
    fontWeight: '600',
    color: '#B45309',
    lineHeight: 14,
    flexShrink: 1,
  },
  dealActionControl: {
    width: 96,
    flexShrink: 0,
  },
  dealActionControlExpanded: {
    width: 132,
  },
  dealPlusMiniBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0D9488',
    borderRadius: 22,
    paddingHorizontal: 5,
    paddingVertical: 2,
    marginLeft: 6,
  },
  dealPlusMiniText: {
    fontSize: 9.5,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  dealPopularMiniBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ECFDF5',
    borderRadius: 22,
    paddingHorizontal: 5,
    paddingVertical: 2,
    marginLeft: 6,
  },
  dealPopularMiniText: {
    fontSize: 9.5,
    fontWeight: '800',
    color: '#047857',
  },
  dealRatingVal: {
    fontSize: 12,
    fontWeight: '600',
    color: '#4B5563',
    flexShrink: 0,
  },
  dealReviewsText: {
    fontSize: 12,
    fontWeight: '500',
    color: '#9CA3AF',
    flexShrink: 0,
  },
  dealPopularBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ECFDF5',
    paddingHorizontal: 6,
    paddingVertical: 1.5,
    borderRadius: 22,
  },
  dealPopularBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#047857',
  },

  // Urgency Deadstock elements
  stockProgressContainer: {
    marginTop: 4,
    marginBottom: 3,
    gap: 3,
  },
  stockProgressBarBackground: {
    height: 4,
    width: '100%',
    backgroundColor: '#F3F4F6',
    borderRadius: 22,
    overflow: 'hidden',
  },
  stockProgressBarFill: {
    height: '100%',
    backgroundColor: '#F59E0B',
    borderRadius: 22,
  },
  stockText: {
    fontSize: 9.5,
    fontWeight: '700',
    color: '#D97706',
  },

  dealPriceVal: { fontSize: 15, fontWeight: '800', color: '#111827' },
  dealOriginalPriceVal: { fontSize: 12, fontWeight: '500', color: '#9CA3AF', textDecorationLine: 'line-through' },

  savingsBadge: {
    backgroundColor: '#ECFDF5',
    paddingHorizontal: 8,
    paddingVertical: 3.5,
    borderRadius: 22,
    alignSelf: 'flex-start',
    marginTop: 2,
    marginBottom: 4,
  },
  savingsBadgeText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#047857',
  },

  addButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F3F4F6',
    height: 34,
    borderRadius: 22,
    width: '100%',
  },
  addButtonText: {
    fontSize: 12.5,
    fontWeight: '700',
    color: '#1F2937',
  },
  qtyContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F3F4F6',
    height: 34,
    borderRadius: 22,
    marginTop: 5,
    paddingHorizontal: 6,
  },
  qtyRowContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    width: '100%',
  },
  qtySelector: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F3F4F6',
    height: 34,
    borderRadius: 22,
    paddingHorizontal: 4,
    minWidth: 0,
  },
  deleteSelectionBtn: {
    width: 34,
    height: 34,
    flexShrink: 0,
    borderRadius: 22,
    backgroundColor: '#FEE2E2',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#FCA5A5',
  },
  qtyBtn: {
    width: 26,
    height: 26,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  qtyText: {
    fontSize: 13,
    fontWeight: '800',
    color: '#1F2937',
  },
  flashBadge: {
    backgroundColor: '#EF4444',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 22,
  },
  flashBadgeText: {
    color: '#FFFFFF',
    fontSize: 9.5,
    fontWeight: '900',
  },

  impactBanner: { backgroundColor: '#ECFDF5', padding: 16, borderRadius: 22, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 },
  impactContent: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  impactTitle: { fontSize: 16, fontWeight: '800', color: '#065F46' },
  impactSubtitle: { fontSize: 12, fontWeight: '500', color: '#047857' },
  impactStats: { alignItems: 'flex-end' },
  impactStatValue: { fontSize: 18, fontWeight: '900', color: '#059669' },
  impactStatLabel: { fontSize: 10, fontWeight: '700', color: '#10B981', textTransform: 'uppercase' },

  mysteryCard: { width: 280, height: 160, borderRadius: 22, overflow: 'hidden', backgroundColor: '#F3F4F6' },

  rescuerItem: { width: 90, alignItems: 'center', gap: 8 },
  rescuerAvatarWrapper: {
    width: 70,
    height: 70,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    overflow: 'hidden'
  },
  rescuerAvatar: { width: '100%', height: '100%', borderRadius: 22, backgroundColor: '#F3F4F6' },
  medalBadge: {
    position: 'absolute',
    bottom: -4,
    right: -4,
    backgroundColor: '#3B82F6',
    width: 20,
    height: 20,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: '#FFF'
  },
  rescuerName: { fontSize: 13, fontWeight: '700', color: '#1F2937', marginTop: 2, textAlign: 'center' },
  rescuerPoints: { fontSize: 11, fontWeight: '500', color: '#9CA3AF', textAlign: 'center' },

  homeStampWidget: {
    backgroundColor: '#FDF2F4', // Matches pointsPill signature soft pink wash
    borderWidth: 1.5,
    borderColor: '#FCE7EC', // Smooth border
    borderRadius: 22,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginBottom: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#5B2333', // Subtle pink shadow for high-end glow
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
  },
  homeStampLeft: {
    gap: 3,
  },
  homeStampHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  homeStampTitle: {
    fontSize: 13.5,
    fontWeight: '800', // Stronger, more professional bolding
    color: '#5B2333', // Matching header text accent
  },
  homeStampSubtitle: {
    fontSize: 11.5,
    fontWeight: '600',
    color: 'rgba(91, 35, 51, 0.7)', // Harmonious semi-transparent burgundy
  },
  homeStampRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  homeStampSlots: {
    flexDirection: 'row',
    gap: 5,
  },

  premiumBanner: {
    backgroundColor: '#F3F4F6',
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderRadius: 22,
    marginBottom: 24,
    flexDirection: 'column',
    alignItems: 'stretch',
    overflow: 'hidden',
    gap: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  premiumTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  premiumLogoRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  premiumLogoText: { color: '#1F2937', fontSize: 18, fontWeight: '900', letterSpacing: -0.5 },
  premiumPlusBadge: { backgroundColor: '#FFD700', paddingHorizontal: 4, borderRadius: 22 },
  premiumPlusText: { color: '#5B2333', fontSize: 14, fontWeight: '900' },
  premiumBenefitsList: {
    gap: 6,
    marginTop: 2,
  },
  premiumBenefitItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  premiumBenefitText: {
    color: '#4B5563',
    fontSize: 12,
    fontWeight: '600',
  },
  premiumCTAButtonThin: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 12,
    height: 36,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    minWidth: 100,
  },
  premiumCTABtnTextThin: {
    color: '#1F2937',
    fontSize: 12.5,
    fontWeight: '700'
  },

  aiBanner: {
    backgroundColor: '#FFFFFF',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 22,
    marginBottom: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    overflow: 'hidden',
    gap: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 6,
    elevation: 1,
  },
  aiLeftContent: { flexDirection: 'row', alignItems: 'center', gap: 12, flex: 1, overflow: 'hidden' },
  aiLogoRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  aiTitle: { color: '#1F2937', fontSize: 13.5, fontWeight: '800', letterSpacing: -0.5 },
  aiBetaBadge: { backgroundColor: '#111827', paddingHorizontal: 5, paddingVertical: 1.5, borderRadius: 22 },
  aiBetaText: { color: '#FFFFFF', fontSize: 8, fontWeight: '900', letterSpacing: 0.2 },
  aiSubtitle: { color: '#4B5563', fontSize: 12.5, fontWeight: '600', flexShrink: 1 },
  aiCTAButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#111827',
    paddingHorizontal: 14,
    height: 36,
    borderRadius: 22,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 2,
  },
  aiCTABtnText: {
    color: '#FFFFFF',
    fontSize: 12.5,
    fontWeight: '800'
  },

  brandLogoCard: { width: 100, height: 60, backgroundColor: '#F9FAFB', borderRadius: 22, alignItems: 'center', justifyContent: 'center', padding: 12 },
  brandLogo: { width: '100%', height: '100%' },

  tipCard: {
    width: 220,
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    overflow: 'hidden',
  },
  tipImage: {
    width: '100%',
    height: 120,
    backgroundColor: '#F3F4F6',
  },
  tipInfo: {
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 12,
    gap: 6,
  },
  tipTitle: { fontSize: 14, fontWeight: '700', color: '#1F2937', lineHeight: 18 },
  tipTimeRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  tipTime: { fontSize: 11, fontWeight: '500', color: '#9CA3AF' },

  recentItem: { width: 140, gap: 8 },
  recentImage: { width: 140, height: 140, borderRadius: 22, backgroundColor: '#F3F4F6' },
  recentLine: { height: 8, backgroundColor: '#F3F4F6', borderRadius: 22, width: '90%' },

  newStoreItem: { width: 120, gap: 6 },
  newStoreImage: { width: 120, height: 120, borderRadius: 22, backgroundColor: '#F3F4F6' },
  newStoreBadge: { position: 'absolute', top: 0, right: 0, backgroundColor: '#10B981', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 22 },
  newStoreBadgeText: { color: '#FFF', fontSize: 10, fontWeight: '800' },
  newStoreName: { fontSize: 14, fontWeight: '700', color: '#1A1A1A', textAlign: 'center', marginTop: 4 },
  newStoreCat: { fontSize: 12, color: '#6B7280', textAlign: 'center' },

  // El Estilo del Barrio Premium Lookbook Styling
  lookbookHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginTop: 22,
    marginBottom: 6,
  },
  lookbookTitleContainer: {
    flexDirection: 'column',
    flex: 1,
  },
  lookbookSectionTitle: {
    fontSize: 18.5,
    fontWeight: '800',
    color: '#111827',
    letterSpacing: -0.5,
  },
  lookbookSectionSubtitle: {
    fontSize: 12,
    color: '#6B7280',
    fontWeight: '500',
    marginTop: 2,
    lineHeight: 16,
  },
  lookbookTabsContainer: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    marginTop: 12,
    gap: 8,
  },
  lookbookTabButton: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 22,
    backgroundColor: '#F3F4F6',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  lookbookTabButtonActive: {
    backgroundColor: '#111827',
    borderColor: '#111827',
  },
  lookbookTabText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#4B5563',
  },
  lookbookTabTextActive: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  lookbookCanvasCard: {
    marginHorizontal: 20,
    marginTop: 14,
    marginBottom: 24,
    borderRadius: 22,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    overflow: 'hidden',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 4,
    height: 480,
    position: 'relative',
  },
  lookbookImage: {
    width: '100%',
    height: '100%',
    position: 'absolute',
  },
  hotspotContainer: {
    position: 'absolute',
    width: 32,
    height: 32,
    marginLeft: -16,
    marginTop: -16,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
  },
  hotspotPulse: {
    position: 'absolute',
    width: 32,
    height: 32,
    borderRadius: 22,
    backgroundColor: '#A855F7',
  },
  hotspotDot: {
    width: 24,
    height: 24,
    borderRadius: 22,
    backgroundColor: '#A855F7',
    borderWidth: 2,
    borderColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  hotspotDotActive: {
    backgroundColor: '#111827',
    borderColor: '#FFFFFF',
  },
  tooltipCard: {
    position: 'absolute',
    bottom: 38,
    left: -90,
    width: 212,
    padding: 12,
    borderRadius: 22,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.6)',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 6,
    zIndex: 20,
  },
  tooltipHeader: {
    marginBottom: 6,
  },
  tooltipName: {
    fontSize: 13,
    fontWeight: '700',
    color: '#111827',
  },
  tooltipStore: {
    fontSize: 11,
    color: '#6B7280',
    fontWeight: '500',
  },
  tooltipPricingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 4,
  },
  tooltipPriceGroup: {
    flexDirection: 'column',
  },
  tooltipPrice: {
    fontSize: 14,
    fontWeight: '800',
    color: '#111827',
  },
  tooltipOrigPrice: {
    fontSize: 11,
    color: '#9CA3AF',
    textDecorationLine: 'line-through',
  },
  tooltipAddBtn: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 22,
    backgroundColor: '#A855F7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  tooltipAddBtnActive: {
    backgroundColor: '#10B981',
  },
  tooltipAddBtnText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '700',
  },
  tooltipAddBtnTextActive: {
    color: '#FFFFFF',
  },
  lookbookComboBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(17, 24, 39, 0.95)',
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomLeftRadius: 22,
    borderBottomRightRadius: 22,
  },
  comboInfoColumn: {
    flexDirection: 'column',
    flex: 1,
    marginRight: 10,
  },
  comboTitle: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
  comboSavings: {
    color: '#10B981',
    fontSize: 11,
    fontWeight: '600',
    marginTop: 1,
  },
  comboPriceWrapper: {
    alignItems: 'flex-end',
    marginRight: 12,
  },
  comboOriginalPrice: {
    color: '#9CA3AF',
    fontSize: 11,
    textDecorationLine: 'line-through',
  },
  comboPriceText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
  },
  comboAddButton: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 22,
    backgroundColor: '#A855F7',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 105,
  },
  comboAddButtonActive: {
    backgroundColor: '#10B981',
  },
  comboAddButtonText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
  },
  comboAddButtonTextActive: {
    color: '#FFFFFF',
  },
  floatingCartContainer: {
    position: 'absolute',
    bottom: 20,
    left: 0,
    right: 0,
    alignItems: 'center',
    zIndex: 999,
  },
  floatingButtonsContainer: {
    position: 'absolute',
    bottom: 20,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 12,
    zIndex: 999,
  },
  floatingSearchPill: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    height: 44,
    borderRadius: 22,
    paddingHorizontal: 18,
    borderWidth: 1.5,
    borderColor: '#5B2333',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.38,
    shadowRadius: 24,
    elevation: 16,
    gap: 8,
  },
  floatingCartPill: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center', // Center content when auto-sizing
    backgroundColor: '#FFFFFF',
    height: 44, // Slightly lower height for maximum compact feel
    borderRadius: 22,
    paddingHorizontal: 16,
    borderWidth: 1.5,
    borderColor: '#5B2333',
    gap: 16, // Distinct narrow gap between left and right sections instead of spanning the screen
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 12 }, // Maximum elegant displacement
    shadowOpacity: 0.38, // Very strong shadow opacity for ultimate prominence
    shadowRadius: 24, // Wide, deep premium glow
    elevation: 16, // Maximum elevation for Android
  },
  cartBadgeWrapper: {
    backgroundColor: '#5B2333', // Accent color badge background
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    paddingHorizontal: 4.5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cartBadgeText: {
    color: '#FFFFFF', // White text on accent badge
    fontSize: 10,
    fontWeight: '800',
    lineHeight: 12,
  },
  floatingCartText: {
    color: '#5B2333', // Accent color text for a cohesive look
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: -0.2,
  },
  floatingCartPrice: {
    color: '#5B2333', // Accent color price
    fontSize: 14.5,
    fontWeight: '800',
  },
  floatingCartSeparator: {
    width: 1,
    height: 14,
    backgroundColor: '#E5E7EB',
    marginHorizontal: 2,
  },
});
