-- Create categories table
create table public.categories (
    id bigint generated by default as identity primary key,
    title text not null,
    emoji text not null,
    is_ai boolean default false not null,
    order_index integer default 0 not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.categories enable row level security;

-- Create policy to allow everyone to read categories
create policy "Allow public read access to categories"
on public.categories
for select
using (true);

-- Insert initial categories
insert into public.categories (title, emoji, is_ai, order_index) values
('Moda', '👗', false, 1),
('Tech', '💻', false, 2),
('Hogar', '🏠', false, 3),
('Deportes', '🏀', false, 4),
('Belleza', '💄', false, 5),
('Cercle AI', '✨', true, 6);
